/**
 * @description       : Unit tests for the LwrCca_TaxConfiguration class.
 * @author            : Code-It-Forward team members (main contributors) and Tom Zarr (content adaptation and editing for course)
 *                      To find out more about Code-It-Forward please consult these links:
 *                      https://sfdc.co/CodeItForwardCharter
 *                      https://sfdc.co/CodeItForwardRepository
 * @group             : Salesforce Commerce Partner Enablement Success
 * @last modified on  : 07-01-2026
 * @last modified by  : Tom Zarr
**/
@IsTest
public class LwrCca_TaxConfiguration_Test
{
    @testSetup
    static void setup()
    {
        WebStore webStore = new WebStore(
            Name = 'B2B Store',
            Tax_Document_Type__c ='Quotation',
            Tax_Transaction_Type__c ='Sale'
        );
        insert webStore;
    }

    @isTest
    static void testgetMetaDataDTO()
    {
        WebStore webStore = [SELECT Id FROM WebStore WHERE Name = 'B2B Store' LIMIT 1];
        String name = 'B2B Store';
        Tax_Provider__mdt taxMeta = getCustomMetadataRecord(name);
        Test.startTest();
        LwrCca_TaxMetaData result = LwrCca_TaxConfiguration.getMetaDataDTO(webStore.Id, 'Sale', 'Quotation');
        System.assert(result != null);
        Test.stopTest();
    }

    @isTest
    static void testgetMetaDataObject()
    {
        Test.startTest();
        Tax_Provider__mdt metaProviderData = LwrCca_TaxConfiguration.getMetaDataObject();
        System.assert(metaProviderData == null);
        Test.stopTest();
    }

    public static Tax_Provider__mdt getCustomMetadataRecord(String myName)
    {
        System.debug('### Tax_Provider__mdt getCustomMetadataRecord(String ' + myName + ') called');

        Tax_Provider__mdt testTaxProvider = new Tax_Provider__mdt
        (
            Context_Name__c = myName,
            Context_Locale__c = 'en_US',
            Taxation_Policy__c = 'Standard',
            Customer_Code__c = 'Cust123',
            Company_Code__c = 'Comp456',
            Shipping_Items_Taxable__c = true,
            Default_Shipping_Tax_Code__c = 'ShippingTax',
            Default_Product_Tax_Code__c = 'ProductTax',
            Consider_product_tax_codes__c = true,
            Product_Tax_Exemption__c = false,
            Customer_Tax_Exemption__c = true,
            Document_Type__c = 'Quotation',
            Transaction_Type__c = 'Sale',
            Commit__c = true,
            Address_Line1__c = '123 Test St',
            Address_Line2__c = 'Suite 100',
            City__c = 'Test City',
            State__c = 'Test State',
            Zip_Code__c = '12345',
            Country_Code__c = 'USA',
            Impl_Class__c = 'TestImplClass',
            Request_Template__c = '{"request": "template"}'
      	);

        System.debug('testTaxProvider JSON:');
        System.debug('---------------------');
        System.debug(JSON.serializePretty(testTaxProvider));

        return testTaxProvider;
    }
}